baseURL = 'https://veldrane.github.io/'
languageCode = 'en-us'
title = '-veldrane'
theme = 'risotto'
relativeURLs = true

[params]
sectionPagesMenu = "main"

[security]
enableInlineShortcodes = true

[menu]
  [[menu.main]]
  identifier = "projects"
  name = "projects"
  url = "/projects/"
  weight = 1

  [[menu.main]]
  identifier = "slides"
  name = "slides"
  url = "/slides/"
  weight = 2

  [[menu.main]]
  identifier = "ham"
  name = "ham"
  url = "/ham/"
  weight = 3
