baseURL = 'https://veldrane.github.io/'
title = '-veldrane'
theme = 'risotto'
relativeURLs = true
lang= "en"
languageCode = "en"
DefaultContentLanguage = "en"
copyright = "© -veldrane"

[params]
sectionPagesMenu = "main"
palette = "tender"

[security]
enableInlineShortcodes = true


[params.about]
title = "email and github"
description = "Feel free to contact me at:"
# unicode/emoji logo:
logo = "📡"

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/veldrane"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:gveldrane@gmail.com"

[menu]
  [[menu.main]]
  identifier = "projects"
  name = "projects"
  url = "/projects/"
  weight = 1

  [[menu.main]]
  identifier = "slides"
  name = "slides"
  url = "/slides/"
  weight = 2

  [[menu.main]]
  identifier = "ham"
  name = "ham"
  url = "/ham/"
  weight = 3

  [[menu.main]]
  identifier = "dancing"
  name = "dancing"
  url = "/dancing/"
  weight = 4

    [[menu.main]]
  identifier = "history"
  name = "history"
  url = "/history/"
  weight = 5