baseURL = 'https://veldrane.github.io/'
languageCode = 'en-us'
title = '-veldrane'
theme = 'risotto'
relativeURLs = false
canonifyURLs = false

[menu]
  [[menu.main]]
  identifier = "projects"
  name = "projects"
  url = "/projects/"
  weight = 1

  [[menu.main]]
  identifier = "slides"
  name = "slides"
  url = "/slides/"
  weight = 2